spring:
  profiles:
    active:
      - EN
      - cat
      - dev
guru:
  username: ymlUsername
  password: ymlPassword
  jdbcurl:  ymljdbcurl

---
spring:
  profiles: prod

guru:
  username: ymlProdUsername
  password: ymlProdPassword
  jdbcurl:  ymlPrdojdbcurl
